### ISSUE TITLE
ValueError: cannot reshape array of size 2559968 into shape (176,10,2048)

### ISSUE THREAD

**Issue by Karimhar** [tianyu0207/RTFM#26]
When I train on UCF-Crime I get this error, is it due to a damaged file? I had a hard time downloading your files by the way.

Thank you :-)

`Traceback (most recent call last):

  File "/home/quadro_6000/Téléchargements/RTFM-main/main.py", line 59, in <module>
    train(loadern_iter, loadera_iter, model, args.batch_size, optimizer, viz, device)

  File "/home/quadro_6000/Téléchargements/RTFM-main/train.py", line 109, in train
    ninput, nlabel = next(nloader)

  File "/home/quadro_6000/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()

  File "/home/quadro_6000/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration

  File "/home/quadro_6000/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "/home/quadro_6000/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "/home/quadro_6000/Téléchargements/RTFM-main/dataset.py", line 39, in __getitem__
    features = np.load(self.list[index].strip('\n'), allow_pickle=True)

  File "/home/quadro_6000/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 440, in load
    return format.read_array(fid, allow_pickle=allow_pickle,

  File "/home/quadro_6000/anaconda3/lib/python3.8/site-packages/numpy/lib/format.py", line 783, in read_array
    array.shape = shape

ValueError: cannot reshape array of size 2559968 into shape (176,10,2048)`

**Comment by MTanveerR** [comment]
Dear Sir Karimhar, the same problem is encountered with me, please could you guide how this error can be solved.?
