### ISSUE TITLE
expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by DungVo1507** [tianyu0207/RTFM#47]
Hello @tianyu0207,
I am using your RTFM method to evaluate my dataset but I made an error like this:
`RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
`
Is it because my pytorch version and yours are different?
Can you tell me its problem?
Thank you so much!

**Comment by DungVo1507** [comment]
More specifically,
I made an error like this:
```
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    train(loadern_iter, loadera_iter, model, args.batch_size, optimizer, viz, device)
  File "/home/object_detection/ViDung/RTFM_myData/train.py", line 108, in train
    ninput, nlabel = next(nloader)
  File "/home/object_detection/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/object_detection/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 560, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/object_detection/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/object_detection/.local/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/home/object_detection/.local/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 124, in __iter__
    yield from torch.randperm(n, generator=generator).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

```

**Comment by daviduarte** [comment]
Change shuffle = True to shuffle = False in the main.py. In other word, this

```
    train_nloader = DataLoader(Dataset(args, test_mode=False, is_normal=True),
                               batch_size=args.batch_size, shuffle=True,
                               num_workers=0, pin_memory=False, drop_last=True)
    train_aloader = DataLoader(Dataset(args, test_mode=False, is_normal=False),
                               batch_size=args.batch_size, shuffle=True,
                               num_workers=0, pin_memory=False, drop_last=True)
    test_loader = DataLoader(Dataset(args, test_mode=True),
                              batch_size=1, shuffle=False,
                              num_workers=0, pin_memory=False)
```

becames

```
    train_nloader = DataLoader(Dataset(args, test_mode=False, is_normal=True),
                               batch_size=args.batch_size, shuffle=False,
                               num_workers=0, pin_memory=False, drop_last=True)
    train_aloader = DataLoader(Dataset(args, test_mode=False, is_normal=False),
                               batch_size=args.batch_size, shuffle=False,
                               num_workers=0, pin_memory=False, drop_last=True)
    test_loader = DataLoader(Dataset(args, test_mode=True),
                              batch_size=1, shuffle=False,
                              num_workers=0, pin_memory=False)
```
